### ISSUE TITLE
MU state Matrix  : 4th position w=1

### ISSUE THREAD

**Issue by CreaperLost** [denniskb/hy475#1]
So the matrix given is  this.mu = [200, 200, 0, 1];
comment is //state = [x, y, dir, w=1]
what is the meaning of w?
what does it represent?

**Comment by denniskb** [comment]
w is a 'homogenizing constant' used in algebra to distinguish between points and directions. A directional vector has a w=0 so multyplying it with a translation matrix for example won't have any effect, while a point (a location/position) has a w=1 which is affected by, among other things, translation matrices.

The state vector `mu` is supposed to have a constant 4th component =1 for the sole purpose of making the multiplication with the state transition matrix `A` work. It should never change or have any influence on any other calculations in the Kalman filter.

**Extra tip**
In a previous exercise you wrote the following code:

```javascript
this.x += 2 * math.cos(this.dir);
this.y -= 2 * math.sin(this.dir);
this.dir += deltaDir;
```

In the Kalman filter you should define matrices `A`, `B`, and `u` so that the expression `mu = A*mu + B*u` has **the exact same effect** as the 3 lines of code above!

**Comment by denniskb** [comment]
Here's a brief [article](https://www.javatpoint.com/computer-graphics-3d-transformations) on positional vectors and translation matrices which should make the purpose of `w` absolutely clear.

**Comment by Eleanna-ph5068** [comment]
Hello. I would like to ask you about B and u matrices. Isn't it right that B is an (4x1) and u an (1x1) matrix? 
Our control input is "deltaDir", isn't it? (Please forgive me if i am not allowed to ask about the answer and give me same clues)
Thank you!

**Comment by denniskb** [comment]
@Eleanna-ph5068 `A*mu` yields a 4x1 matrix so `B*u` must also result in a 4x1 matrix in order to be able to add the two together. Also, my [previous answer](https://github.com/denniskb/hy475/issues/1#issuecomment-792057574) in this thread will give you an additional clue about the shape of `B` and `u` ;-) That's as much as I can say without outright revealing the solution..

> Our control input is "deltaDir", isn't it?

"`predict()` is invoked on every simulation step and is passed the (requested) relative change in direction in radians *`deltaDir`* (**aka steering/control input**)..."
