### ISSUE TITLE
Step 4 questions

### ISSUE THREAD

**Issue by grasstr8** [denniskb/hy475#14]
Hi,
I have a problem in understanding the implementation in step 4.
The bucket is the prefix sum of the weights, but how is this equivalent to the second bucket in Figure 1?
Since bucket is the prefix sum, then bucket[i+1] has always larger size that bucket[i] but that doesn't mean that weight i+1 is larger than weight i.
So I don't understand why prefix sum scales proportionally to the particles' weights.
Also about the low-variance sampling. Let's say i=2 and r=1. then we will draw from bucket r+i/N=1.02. Does this mean that we draw from bucket[1]?
Finally in the method Array.lowerBound(x), why do we need to return the lowest element x?

Thank you

**Comment by denniskb** [comment]
Imagine you're writing an AI for a video game and you randomly want to decide between one of two actions. All you have available is a `rand()` functions which generates *uniformly distributed* random (real) numbers on the interval `(0, 1]`. You code:

```
if (rand() <= 0.5)
    actionA();
else
    actionB();
```

Given a good RNG and lots of iterations, this will choose action A in *roughly* half of all iterations. Now let's say you want your AI to perform action A 3x more likely than action B, you simply change the threshold:

```
if (rand() <= 0.75)
    actionA();
else
    actionB();
```

Let's say we want our AI to choose between 3 actions A, B, and C with weights 10, 3, and 7. We would write:

```
r = rand();
if (r <= 0.5)        // 10/20
    actionA();
else if (r <= 0.65)  // (10+3)/20
    actionB();
else  // if (r <= 1) // (10+3+7)/20
    actionC();
```

See how the thresholds 0.5, 0.65 (, and 1) are equivalent to the prefix sum of the **normalized** weights (remember that our particle weights are already normalzied?)? Using the prefix sum (intuitively buckets) is just the generalization of the above technique, sparing us from having to write `N=100` `if`-cases (and rewriting them everytime `N` changes).

Binary search (in the form of `Array.lowerBound()`) is just an efficient way to find the correct bucket (/the correct `if`-case). If you think about it our `if`-`else`-structure does exactly the same thing: It "finds" the first (i.e. the smallest) threshold >= `r`.

**Comment by denniskb** [comment]
To add some more clarifications just in case..

> Since bucket is the prefix sum, then bucket[i+1] has always larger size that bucket[i] but that doesn't mean that weight i+1 is larger than weight i.

The values in the buckets (the prefix sum) do not represent the buckets' weights, the particle weights represent the buckets' weights. The values in the buckets represent their *boundaries*.

> Also about the low-variance sampling. Let's say i=2 and r=1. then we will draw from bucket r+i/N=1.02. Does this mean that we draw from bucket[1]?

You don't draw based on the bucket's index, but based on its value. r=1, by definition, will always draw from the last bucket, since the bucket weights sum to 1:

```
|-----|-----|-----|--x--|-----|
0    .2    .4    .6    .8     1

|--|--|--------|--|--x--------|
0 .1 .2       .5 .6           1
```
*Uniform sampling (top): All buckets have the same weight 0.2, their boundaries are defined by i\*0.2 We draw a random number x=0.75 and select the bucket if falls into, in this case `buckets[3]`. Since all buckets have the same size we can calculate the index simply via `floor(x/0.2)`. Weighted sampling (bottom): The buckets have arbitrary weights, their boundaries are defind by the prefix sum. We can no longer calculate the index of the bucket that contains x arithmetically, but need to search for it. It's the first (/smallest) bucket whose right boundary >= x (the prefix sum calculates right boundaries). We could simply loop through our `buckets` array until we find the first one >= x, or, more efficiently, we can use binary search.*

**Comment by grasstr8** [comment]
That was really helpful, thank you!
