### ISSUE TITLE
Steps 2&3 questions

### ISSUE THREAD

**Issue by grasstr8** [denniskb/hy475#15]
Hi,

The altitude of the particles with respect to the sea level as far I understood is also altsea right? If not, is it random and why do we need altsea and not just compare terrain.at(particle) and terrain.at(aeroplane) ? 
Also is it necessary to use the fact that the highest point of the terrain is 255 m somewhere in our calculations? Could you give as a hint on why do we need it?
Also it is written that: The noise's purpose is to diversify our particles helping them avoid getting stuck in local maxima.
Unfortunately I don't completely understand this. Where does this local maxima refer to? to the altitude?

Thank you in advance

**Comment by denniskb** [comment]
> The altitude of the particles with respect to the sea level as far I understood is also altsea right?

Yes, since the particles represent the plane's location, they naturally have the same altitude as the plane.

> why ... not just compare terrain.at(particle) and terrain.at(aeroplane)

Where do you get `aeroplane` from? `terrain.at()` requires a location. You **don't** have the plane's location. That's the whole point of the particle filter: finding the plane's location.

> why do we need altsea ...

You can use it to find either `terrain.at(aeroplane)` or the particles' `altGround`, which you can then use to calculate your weight.

> Also is it necessary to use the fact that the highest point of the terrain is 255 m

It *could* be useful in your weight calculation since the weight grows anti-proportionally to the discrepancy of altitudes above ground, but it is not strictly necessary.

> Also it is written that: The noise's purpose is to diversify our particles helping them avoid getting stuck in local maxima.

'[maxima](https://en.wikipedia.org/wiki/Maxima_and_minima)' refers to the optimality of the found solution and the convergence of our algorithm to it. The requirement for noise is explained more thorougly in step 4:

> By now, adding random noise to the particles' motions should make sense: If one particle got replicated, say, 3x during resampling, we would end up with 3 identical particles in the next iteration. What's the point of exploring the same hypothesis 3x other than burning CPU cycles? By adding a small amount of noise we turn these 3 copies into independent hypotheses. Resampling has then the effect of concentrating more particles around the plane's probable location which in turn gets explored more heavily compared to other locations. Also, consider that our terrain is 500x500 px, resulting in 250k possible plane locations. We only generate 100 particles. The possiblity that any of them coincides with the plane's location is slim. Without noise, if we didn't happen to generate a particle right at the nose of the plane (very unlikely) we would never be able to converge to the plane's true location.

**Comment by grasstr8** [comment]
This "why do we need altsea and not just compare terrain.at(particle) and terrain.at(aeroplane) ?" was just a question in case the altsea is not the altitude of the particles above sea level. I know that we are looking for the plane's location... but as you wrote I also thought that I can find the terrain.at(aeroplane) using the altsea and altGround and compare it with terrain.at(particle).

Thank you for the answers
