### ISSUE TITLE
clip (/cull) some grid cells

### ISSUE THREAD

**Issue by Eleanna-ph5068** [denniskb/hy475#18]
Good evening,

At Step 3(ii) you ask us to clip (/cull) any grid cells outside our depth sensor's viewing frustum. Is this equivalent to the 6th line of code at slide 10 of our lecture? And last but not least, is  'depth sensor's viewing frustum' equal to 'depth sensor's scanline'?

Thank you a lot!

**Comment by denniskb** [comment]
> Is this equivalent to the 6th line of code at slide 10 of our lecture?

No, it's equivalent to line 3: `if mi in perceptual field of zt then`.

> And last but not least, is 'depth sensor's viewing frustum' equal to 'depth sensor's scanline'?

The depth sensor's viewing frustum is the area that it 'sees'. It is visualized by the yellow, trasnparent cone and defined by the 3x3 projection matrix `eyeToClip`. Please only clip grid cells whose center is either behind the sensor or off to the left/right of its frustum. Do not clip cells inside the frustum no matter how far away they are, even if they are beyond the sensor's "range".

The scanline is the sensor's measurement. Since we're working in 2D it is a 1D array of depth values, equally spaced inside its frustum from left to right (in clockwise direction). If we were working in 3D, the sensor would produce a 2D scan *image* (similar to the example depth map from the Kinect).

**Comment by Eleanna-ph5068** [comment]
I don't understant what I should do in terms of 'skipping'. What does "skip" mean? Otherwords, I don't understand what kind of command I should write after 'if' (case) ->  ... <- ; Do I make my self clear?

**Comment by denniskb** [comment]
The command [`continue;`](https://www.w3schools.com/jsref/jsref_continue.asp) is already provided for you.

**Comment by grasstr8** [comment]
Do you have any other reference about the clipping? In the video you provided it says w_c = z_v, but why is that? I am confused because we compute x_v,y_v but not the z_v...

**Comment by denniskb** [comment]
A vector with clip coordinates `[x, y, z, w]` is inside the frustum *iff* `-w <= x,y,z < w`. Remember that you're *not* supposed to perform full clipping (rejecting every point which breaks *any* of these constraints) but only clip points left/right outside the frustum and behind the observer/sensor.

We project 3D&rArr;2D vectors according to the rule `[x, y, z, w]`&rArr;`[x, z, w]` (i.e. we discard the original `y` and rename `z`&rArr;`y`, or, in other words, our `y` is the original `z`). This is equivalent to looking straight down onto a *flat* 3D world (with its y-axis pointing up).

**Comment by grasstr8** [comment]
Thank you,
Also can you give any hint on why we need the depth.length when we compute xScreen ? In the video it seems that the computation of xScreen is straightforward but I didn't see why we need the sensor's resolution...

**Comment by denniskb** [comment]
NDC range from -1 to 1. You compute a point `xScreen` on that interval, let's say -0.27. How are you gonna know which pixel this value corresponds to without knowing how many pixels there are in total? In the video `depth.length` is called `w` (short for width).
