### ISSUE TITLE
xScreen

### ISSUE THREAD

**Issue by Eleanna-ph5068** [denniskb/hy475#19]
In this video (OpenGL - clip space, NDC, and screen space https://www.youtube.com/watch?v=pThw0S8MR7w), the speaker is refering to x_offset and y_offset. Can you give us some extra information on how we can compute x_offset?

**Comment by denniskb** [comment]
`x_offset` and `y_offset` are used when the focal point of the camera is different from the optical center. Since our virtual camera is "perfect", we don't need those (i.e. they are `0` in our case).

(`x_offset` and `y_offset` come from the Computer Vision world where data is retrieved from imperfect, real cameras whose focal point might be off from the optical center (usually by fractions of a pixel). This defect is typically found after the assembly by a process known as "calibration".)

**Comment by Eleanna-ph5068** [comment]
Thank you!
