### ISSUE TITLE
else if () {} case

### ISSUE THREAD

**Issue by Eleanna-ph5068** [denniskb/hy475#20]
"Add an else if (...) { ... } case after your last if case where you update occupied cells (the one you just modified). Inside the else if case you'll update empty cells instead by incrementing their sum and incrementing their weight, but only cells in front of the measurement."

Why do we update the cells in front of the measurement as empty? Or do I misunderstand?

**Comment by denniskb** [comment]
You understand perfectly. The fact that you're observing/measuring an obstacle at a certain distance *implies* that everything in front of it *must* be empty (otherwise you wouldn't be able to see it, you'd see something else, closer to you):

![z buffer property](https://github.com/denniskb/hy475/raw/master/docs/wiki/issue20.png)

By marking it (multiple times) as empty *now*, we will be able to dismiss noisy (/wrong) measurements inside the same region lateron.

**Comment by Eleanna-ph5068** [comment]
I was thinking in front of the measurement as from the other side (right to the tree). You are right, thank you.
