### ISSUE TITLE
acceleration's value

### ISSUE THREAD

**Issue by mcal1x** [denniskb/hy475#6]
In the picture of the rocket, the 1.4G for the acceleration is depicted but when I am printing the value of the variable with the command console.log(a) I get roughly 3.92 (m/sec^2)
The conversion of the 1.4G to m/sec^2 yields 13.73 m/sec^2
Are all this correct?

**Comment by denniskb** [comment]
You forgot to subtract earth’s gravity of 1G ;)

**Comment by Eleanna-ph5068** [comment]
I use Taylor expansion in place of Euler integration ( first order Taylor expansion), similarly to the dragster example and I observe a MSE : 979 m... If I add 9.8 (m/s^2) to "a" (which is equal to  3.92 m/s^2) my MSE becomes 3807847 m... I understand that's wrong (we try to have a  zero MSE with noise turned off), but mustn't I change the value of "a" so as it is equal to 1.4G?

**Comment by denniskb** [comment]
`a` is a measurement which you're given. You don't change/override measurements, you use them in your calculations. It is already equivalent to 1.4G (after subtracting 1G earth's gravity).

FYI: The dragster example uses **2**nd-order Taylor expansion (and you're supposed to do the same). 1st-order Taylor expansion is the same as Euler and is what's provided in the template ;)

**Comment by Eleanna-ph5068** [comment]
Sorry, I meant _second_ order Taylor expansion in my previous post! Given this, my MSE is 979 m...  I dont know where is the bug. I'll try again.

**Comment by denniskb** [comment]
Just to elaborate a bit: mcal1 was confused why `a` had a value of ~3.9m/s^2, after all the figure in the assignment said "1.4G" and we know that 1.4G = 1.4*9.8m/s^2 ~= 13.7m/s^2. I told them that they forgot to subtract earth's gravity of 1G after which the value makes perfect sense: (1.4G-1G)*9.8m/s^2 ~= 3.9m/s^2.\*\*\*

Refactoring `g1` is (almost) as simple as copy-pasting. If you don't obtain a MSE of 0, you most probably have a simple bug in your code. Double-check it, it's easy to overlook constant factors, etc. (Email me your code so far, perhaps I can give you more concrete feedback than here without revealing the actual solution.)

\*\*\* All objects on earth constantly experience an upward acceleration of 1G, it's what gives us our weight. Otherwise (with 0G as the starting point) we would be floating around weightless. So for a rocket taking off to experience an accel. of 1.4G, considering it's already experiencing 1G just standing on the launch pad, it must be accelerating at (1.4G-1G)*9.8m/s^2. According to Einstein's relativity theory gravity and acceleration are identical: an object undergoing high accel. will experience the same phenomena (space contraction, time dialation, ...) as an object undergoing high gravity.

**Comment by Eleanna-ph5068** [comment]
Alright, thank you.
